const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Tilemap,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Sin,
		C3.Behaviors.Flash,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.destroy,
		C3.Behaviors.jumpthru,
		C3.Plugins.Keyboard,
		C3.Plugins.gamepad,
		C3.Behaviors.Bullet,
		C3.Behaviors.Rotate,
		C3.Plugins.Spritefont2,
		C3.Plugins.Audio,
		C3.Behaviors.Orbit,
		C3.Plugins.Shape3D,
		C3.Plugins.Text,
		C3.Plugins.Particles,
		C3.Plugins.TextBox,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout
	];
};
self.C3_JsPropNameTable = [
	{TiledBackground: 0},
	{TiledBackground2: 0},
	{Tilemap: 0},
	{Janela: 0},
	{Solid: 0},
	{Sine: 0},
	{Suporte: 0},
	{Flash: 0},
	{Platform: 0},
	{Bau: 0},
	{Caixa: 0},
	{Porta: 0},
	{Chave: 0},
	{Bomba: 0},
	{ScrollTo: 0},
	{DestroyOutsideLayout: 0},
	{Jumpthru: 0},
	{Jogador: 0},
	{Sensor_solido: 0},
	{Keyboard: 0},
	{Gamepad: 0},
	{Direcao: 0},
	{Porco_Patrulheiro: 0},
	{Sensor_Patrulheiro_Direita: 0},
	{Sensor_Patrulheiro_Esquerda: 0},
	{Porco_Canhao: 0},
	{Canhao: 0},
	{Bullet: 0},
	{Rotate: 0},
	{Bala: 0},
	{Sensor_Canhao: 0},
	{Vida_HUD: 0},
	{Itens_HUD: 0},
	{Black_Background: 0},
	{Jogador_Dialogo: 0},
	{SpriteFont: 0},
	{Chefao: 0},
	{Audio: 0},
	{Tilemap2: 0},
	{Tilemap3: 0},
	{Porco_Canhao_Esquerda: 0},
	{Canhao_Esquerda: 0},
	{Bala_Esquerda: 0},
	{Porta2: 0},
	{Orbit: 0},
	{Morcego: 0},
	{Bala2: 0},
	{Tilemap4: 0},
	{Tilemap5: 0},
	{Caixa_Correntesa: 0},
	{Suporte2: 0},
	{Caixa_Correntesa2: 0},
	{Caixa2: 0},
	{Suporte3: 0},
	{Caixa_Correntesa3: 0},
	{Tilemap6: 0},
	{Forma3D: 0},
	{Forma3D2: 0},
	{Forma3D3: 0},
	{Forma3D4: 0},
	{Forma3D5: 0},
	{Forma3D6: 0},
	{Forma3D7: 0},
	{Porta3: 0},
	{Parabéns: 0},
	{FonteDeSprites: 0},
	{Partículas: 0},
	{Forma3D8: 0},
	{Texxxto: 0},
	{Vidas: 0}
];

self.InstanceType = {
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	Janela: class extends self.ISpriteInstance {},
	Suporte: class extends self.ISpriteInstance {},
	Bau: class extends self.ISpriteInstance {},
	Caixa: class extends self.ISpriteInstance {},
	Porta: class extends self.ISpriteInstance {},
	Jogador: class extends self.ISpriteInstance {},
	Sensor_solido: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Gamepad: class extends self.IInstance {},
	Porco_Patrulheiro: class extends self.ISpriteInstance {},
	Sensor_Patrulheiro_Direita: class extends self.ISpriteInstance {},
	Sensor_Patrulheiro_Esquerda: class extends self.ISpriteInstance {},
	Porco_Canhao: class extends self.ISpriteInstance {},
	Canhao: class extends self.ISpriteInstance {},
	Bala: class extends self.ISpriteInstance {},
	Sensor_Canhao: class extends self.ISpriteInstance {},
	Vida_HUD: class extends self.ISpriteInstance {},
	Itens_HUD: class extends self.ISpriteInstance {},
	Black_Background: class extends self.ISpriteInstance {},
	Jogador_Dialogo: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	Chave: class extends self.ISpriteInstance {},
	Bomba: class extends self.ISpriteInstance {},
	Chefao: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Tilemap2: class extends self.ITilemapInstance {},
	Tilemap3: class extends self.ITilemapInstance {},
	Porco_Canhao_Esquerda: class extends self.ISpriteInstance {},
	Canhao_Esquerda: class extends self.ISpriteInstance {},
	Bala_Esquerda: class extends self.ISpriteInstance {},
	Porta2: class extends self.ISpriteInstance {},
	Morcego: class extends self.ISpriteInstance {},
	Bala2: class extends self.ISpriteInstance {},
	Tilemap4: class extends self.ITilemapInstance {},
	Tilemap5: class extends self.ITilemapInstance {},
	Caixa_Correntesa: class extends self.ISpriteInstance {},
	Suporte2: class extends self.ISpriteInstance {},
	Caixa_Correntesa2: class extends self.ISpriteInstance {},
	Caixa2: class extends self.ISpriteInstance {},
	Suporte3: class extends self.ISpriteInstance {},
	Caixa_Correntesa3: class extends self.ISpriteInstance {},
	Tilemap6: class extends self.ITilemapInstance {},
	Forma3D: class extends self.I3DShapeInstance {},
	Forma3D2: class extends self.I3DShapeInstance {},
	Forma3D3: class extends self.I3DShapeInstance {},
	Forma3D4: class extends self.I3DShapeInstance {},
	Forma3D5: class extends self.I3DShapeInstance {},
	Forma3D6: class extends self.I3DShapeInstance {},
	Forma3D7: class extends self.I3DShapeInstance {},
	Porta3: class extends self.ISpriteInstance {},
	Parabéns: class extends self.ITextInstance {},
	FonteDeSprites: class extends self.ISpriteFontInstance {},
	Partículas: class extends self.IParticlesInstance {},
	Forma3D8: class extends self.I3DShapeInstance {},
	Texxxto: class extends self.ITextInputInstance {}
}